### ISSUE TITLE
SchemaManager class

### ISSUE THREAD

**Issue by zswgzx** [pyxnat/pyxnat#101]
What is the right way to call the titled class?

Here's what I had:
...
from pyxnat import manage
manage.SchemaManager.add(self=manage.SchemaManager,
                         url='http://central.xnat.org/schemas/xnat/xnat.xsd')

.../pyxnat/core/manage.py", line 131, in add
    etree.fromstring(self._intf._exec(url))
AttributeError: type object 'SchemaManager' has no attribute '_intf'

Btw, where should the .xsd file be put in if I were to add my own customized .xsd?

Thanks in advance!

**Comment by jhuguetn** [comment]
See #27, the right way would be as follows:
```
import pyxnat
central = pyxnat.Interface(...)
c.manage.schemas.add(url='/schemas/xnat/xnat.xsd')
```

Note however that the aforementioned example will solely work with XNAT 1.6.x or below since schemas were moved in 1.7 to the new API (`xapi`) and the URI for accessing them has changed slightly. 
For XNAT 1.7+ do as follows:
```
c.manage.schemas.add(url='/xapi/schemas/xnat')
```

> Btw, where should the .xsd file be put in if I were to add my own customized .xsd?  

You should apply your newly created schema to your XNAT instance first, see [here](https://wiki.xnat.org/documentation/xnat-developer-documentation/working-with-xnat-plugins/developing-xnat-plugins/xnat-data-type-development) to know where to start with.

**Comment by jhuguetn** [comment]
Snap! I have just tested the functionality and I notice it is not working. See below:

```
In [1]: import pyxnat; c = pyxnat.Interface('http://central.xnat.org', anonymous=True)
In [2]: c.manage.schemas.add(url='/xapi/schemas/xnat')
In [3]: p = c.select.project('CENTRAL_OASIS_CS')
In [4]: p.attrs()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d41a1532ffb2> in <module>
----> 1 p.attrs()

.../pyxnat/core/attributes.py in __call__(self)
     46         """
     47         paths = []
---> 48         self._intf.manage.schemas._init()
     49         for root in self._intf.manage.schemas._trees.values():
     50             paths.extend(datatype_attributes(root, self._get_datatype()))

AttributeError: 'SchemaManager' object has no attribute '_init'

```

Opening a new PR with a fix proposal.
